artifact_uri: file:C:/Users/Ahad Ali/Desktop/fraud-detection-mlops/tracking_data/254715740652405066/16cbc59ed6b64518b2d1453cceba841c/artifacts
end_time: 1780514349138
entry_point_name: ''
experiment_id: '254715740652405066'
lifecycle_stage: active
run_id: 16cbc59ed6b64518b2d1453cceba841c
run_name: adventurous-moth-153
source_name: ''
source_type: 4
source_version: ''
start_time: 1780514338221
status: 3
tags: []
user_id: Ahad Ali
